// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// max_clique_cpp
List max_clique_cpp(string graph_file);
RcppExport SEXP _cliqueR_max_clique_cpp(SEXP graph_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type graph_file(graph_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(max_clique_cpp(graph_file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cliqueR_max_clique_cpp", (DL_FUNC) &_cliqueR_max_clique_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cliqueR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
