# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_clique_cpp <- function(graph_file) {
    .Call(`_cliqueR_max_clique_cpp`, graph_file)
}

